
enum types {
    INIT_BOARD = 'INIT_BOARD',
    INCREMENT_TURN = 'INCREMENT_TURN',
    INIT_PLAYERS = 'INIT_PLAYERS',
    RESET_TILEBAG = 'RESET_TILEBAG',
    PLACE_TILE = 'PLACE_TILE',
    REMOVE_TILE_FROM_HAND = 'REMOVE_TILE_FROM_HAND'
}

export default types;
