
enum types {
    INIT_BOARD = 'INIT_BOARD',
    INCREMENT_TURN = 'INCREMENT_TURN',
    INIT_PLAYERS = 'INIT_PLAYERS',
    RESET_TILEBAG = 'RESET_TILEBAG',
    PLACE_TILE_ON_BOARD = 'PLACE_TILE_ON_BOARD',
    REMOVE_TILE_FROM_BOARD = 'REMOVE_FROM_BOARD',
    REMOVE_TILE_FROM_HAND = 'REMOVE_TILE_FROM_HAND',
    PLACE_TILE_IN_HAND = 'PLACE_TILE_IN_HAND'
}

export default types;
