sudo: required
language: node_js

services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  # LTS version
  - "9.3"
install:
  - docker-compose up --build
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
before_script:
- docker-compose up --build -d
script:
  - docker-compose run words-with-friends npm test
after_script:
  - docker-compose down