sudo: required
dist: trusty
language: node_js

services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  # LTS version
  - "8.0"
before_install:
  - npm install npm@latest -g
install:
  - npm install
notifications:
  email:
    on_success: change # only if status change from fail to success
on_failure: always # if there is a fail